apiVersion: v1
kind: Service
metadata:
  name: argocd-lb
  namespace: argocd
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server